name: thigiuaky
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  curved_navigation_bar: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/